theme: jekyll-theme-minimal
title: <img src="https://pijardotai.github.io/img/logo.png" height="180">
description: Your daily dose of AI/Machine Learning updates. Currenlty only avaialable in Bahasa Indonesia.
